services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: AAAaaa111
      POSTGRES_DB: archive
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080